CREATE OR REPLACE FUNCTION create_rxd20_tables()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Drop existing tables if they exist
    DROP TABLE IF EXISTS public.rxd20_token_prices CASCADE;
    DROP TABLE IF EXISTS public.rxd20_price_history CASCADE;
    DROP TABLE IF EXISTS public.rxd20_market_stats CASCADE;

    -- Create new token prices table
    CREATE TABLE IF NOT EXISTS public.rxd20_token_prices (
        symbol TEXT PRIMARY KEY,
        price_usd NUMERIC NOT NULL DEFAULT 0,
        market_cap NUMERIC NOT NULL DEFAULT 0,
        volume_24h NUMERIC DEFAULT 0,
        price_change_24h NUMERIC DEFAULT 0,
        price_change_7d NUMERIC DEFAULT 0,
        last_trade_at TIMESTAMPTZ,
        last_updated TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Create new price history table with 1-minute intervals
    CREATE TABLE IF NOT EXISTS public.rxd20_price_history (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        symbol TEXT NOT NULL,
        price_usd NUMERIC NOT NULL,
        volume NUMERIC DEFAULT 0,
        market_cap NUMERIC,
        timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    -- Create market statistics table
    CREATE TABLE IF NOT EXISTS public.rxd20_market_stats (
        symbol TEXT NOT NULL,
        interval TEXT NOT NULL,
        open_price NUMERIC NOT NULL,
        close_price NUMERIC NOT NULL,
        high_price NUMERIC NOT NULL,
        low_price NUMERIC NOT NULL,
        volume NUMERIC DEFAULT 0,
        timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (symbol, interval)
    );

    -- Create indexes
    CREATE INDEX IF NOT EXISTS idx_price_history_symbol_timestamp 
        ON public.rxd20_price_history (symbol, timestamp DESC);

    CREATE INDEX IF NOT EXISTS idx_market_stats_symbol_interval 
        ON public.rxd20_market_stats (symbol, interval, timestamp DESC);

    -- Enable RLS
    ALTER TABLE public.rxd20_token_prices ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.rxd20_price_history ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.rxd20_market_stats ENABLE ROW LEVEL SECURITY;

    -- Create policies
    DROP POLICY IF EXISTS "Enable read access for all users" ON public.rxd20_token_prices;
    CREATE POLICY "Enable read access for all users" ON public.rxd20_token_prices
        FOR SELECT TO anon USING (true);

    DROP POLICY IF EXISTS "Enable update for users" ON public.rxd20_token_prices;
    CREATE POLICY "Enable update for users" ON public.rxd20_token_prices
        FOR UPDATE TO anon USING (true);

    DROP POLICY IF EXISTS "Enable read access for all users" ON public.rxd20_price_history;
    CREATE POLICY "Enable read access for all users" ON public.rxd20_price_history
        FOR SELECT TO anon USING (true);

    DROP POLICY IF EXISTS "Enable insert for users" ON public.rxd20_price_history;
    CREATE POLICY "Enable insert for users" ON public.rxd20_price_history
        FOR INSERT TO anon WITH CHECK (true);

    DROP POLICY IF EXISTS "Enable read access for all users" ON public.rxd20_market_stats;
    CREATE POLICY "Enable read access for all users" ON public.rxd20_market_stats
        FOR SELECT TO anon USING (true);

    DROP POLICY IF EXISTS "Enable update for users" ON public.rxd20_market_stats;
    CREATE POLICY "Enable update for users" ON public.rxd20_market_stats
        FOR UPDATE TO anon USING (true);
END;
$$;