-- Create tables function
create or replace function create_tables()
returns void
language plpgsql
security definer
as $$
begin
  -- Create orders table if it doesn't exist
  create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    from_token text not null,
    to_token text not null,
    from_amount numeric not null,
    to_amount numeric not null,
    swap_tx text not null,
    claimed boolean default false,
    claim_count integer default 0,
    status text default 'active',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
  );

  -- Enable RLS
  alter table public.orders enable row level security;

  -- Create policies
  drop policy if exists "Enable read access for all users" on public.orders;
  create policy "Enable read access for all users" on public.orders
    for select to anon using (true);

  drop policy if exists "Enable insert for all users" on public.orders;
  create policy "Enable insert for all users" on public.orders
    for insert to anon with check (true);

  drop policy if exists "Enable update for all users" on public.orders;
  create policy "Enable update for all users" on public.orders
    for update to anon using (true);
end;
$$;