-- Create wallet_addresses table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.wallet_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS
ALTER TABLE public.wallet_addresses ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for all users" ON public.wallet_addresses
  FOR SELECT TO anon USING (true);

CREATE POLICY "Enable insert for all users" ON public.wallet_addresses
  FOR INSERT TO anon WITH CHECK (true);

-- Add initial test wallet
INSERT INTO public.wallet_addresses (address)
VALUES ('1PhM4yjL9PXGoJxo6qfx8JbaEM3NPaF5Bt')
ON CONFLICT (address) DO NOTHING;

-- Add wallet_address column to orders table
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS wallet_address TEXT,
ADD COLUMN IF NOT EXISTS claimed_by TEXT,
ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMPTZ;