-- Create tokens table with proper schema
CREATE TABLE IF NOT EXISTS public.tokens (
  symbol TEXT PRIMARY KEY,
  price_usd NUMERIC NOT NULL DEFAULT 0,
  market_cap NUMERIC NOT NULL DEFAULT 0,
  last_updated TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Create token_price_history table
CREATE TABLE IF NOT EXISTS public.token_price_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol TEXT NOT NULL,
  price_usd NUMERIC NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_token_price_history_symbol_timestamp 
  ON token_price_history (symbol, timestamp);

-- Enable RLS
ALTER TABLE public.tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.token_price_history ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for all users" ON public.tokens
  FOR SELECT TO anon USING (true);

CREATE POLICY "Enable update for all users" ON public.tokens
  FOR UPDATE TO anon USING (true);

CREATE POLICY "Enable insert for all users" ON public.tokens
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.token_price_history
  FOR SELECT TO anon USING (true);

CREATE POLICY "Enable insert for all users" ON public.token_price_history
  FOR INSERT TO anon WITH CHECK (true);